### ISSUE TITLE
Create a system for tracking the data migration

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1061]
## Acceptance Criteria
- [x] we can easily tell what issues are on the critical path before we can start the data migration
  - [x] Use the `dataspace migration` label on github 
- [x] there is a spreadsheet that includes every work that needs migration
- [x] there is a clearly documented place where we can track what has been migrated
- [x] there is an agreed upon set of steps for each work that needs migration
- [x] there is clear documentation for any data augmentation that needs to happen
- [x] we can prioritize PPPL works and do them first
