### ISSUE TITLE
Generate spreadsheets for migration tracking

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1097]
In order to distribute the work for DataSpace --> PDC Describe data migration, we need to generate spreadsheets of all of the items that need migration. 

## Acceptance criteria
- [x] it will use the same list used by PDC Discovery: https://github.com/pulibrary/pdc_discovery/blob/main/config/collections.csv
- [x] we will generate a spreadsheet for each "community" as defined by the dspace number
- [x] the spreadsheet will contain the following columns:
  - [x] collection name
  - [x] community name(s)
  - [x] ark
  - [x] title
  - [x] DOI from OSTI 
  - [x] re-described (boolean; i.e., "has this item been re-described in PDC Describe yet?) 
  - [x] PDC Describe id (once it has been re-described in PDC Describe it will have a PDC Describe database id, which we'll need for moving the data)
  - [x] data migrated (boolean; i.e., "has the data payload been moved?")

Details of any back and forth around metadata or problems with data migration should happen in the PDC Describe record so we can exercise the functionality of using the interface as much as possible.

**Comment by kelynch** [comment]
Of possible use for reference:

* [Launch plan](https://docs.google.com/document/d/1f79682y1zLllal9My6IHG74zSTVWzEbmMl4xGTKwBOY/edit#)
* [Collection migration tracking](https://docs.google.com/spreadsheets/d/148EHw1FuYhd4kqov5UA04cpSekMGGlAy3zakBwuowFo/edit#gid=0)
