### ISSUE TITLE
Transition Web Servers to the new Redis Central Service after making sure the current jobs are completed

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1928]
### What maintenance needs to be done?

We will have a new central Redis server for PDC describe after https://github.com/pulibrary/princeton_ansible/issues/5343.  We need to point our web servers at our new central server with care so that we do not lose any jobs on our current individual Redis servers.

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
We want to not longer back up a single server when data gets deposited.  Sharing Redis will allow all servers to work the central queue

### Acceptance criteria
 - [ ] Check the current status of the sidekiq on each server (one at a time)
   - [x]  pdc-describe-prod1
      - [x]  turn off nginx
      - [x]  allow the queue to drain
      - [x] run the [playbook]( https://github.com/pulibrary/princeton_ansible/issues/5344) limiting to just this server 
      - [x] stop and disable local redis `sudo systemctl disable redis-server`
      - [x] start nginx
   - [x]  pdc-describe-prod2
      - [x]  turn off nginx
      - [x]  allow the queue to drain
      - [x] run the [playbook]( https://github.com/pulibrary/princeton_ansible/issues/5344) limiting to just this server 
      - [x]  stop and disable local redis `sudo systemctl disable redis-server`
      - [x] start nginx
   - [x]  pdc-describe-prod3
      - [x]  turn off nginx
      - [x]  allow the queue to drain
      - [x] run the [playbook]( https://github.com/pulibrary/princeton_ansible/issues/5344) limiting to just this server 
      - [x]  stop and disable local redis `sudo systemctl disable redis-server`
      - [x] start nginx

### Implementation notes, if any

Still have some cleanup to do, but at this point all servers should be pointing at the new central Redis

**Comment by carolyncole** [comment]
Fixed as part of https://github.com/pulibrary/princeton_ansible/issues/5344
