### ISSUE TITLE
Convert to a new centralized Redis

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1931]
We want to utilize a central redis server instead of three separate local redis

- [x] [Two servers for new Redis (one for staging one for production)](https://github.com/pulibrary/princeton_ansible/issues/5342)

- [x] [Ansible Playbooks to setup group vars for the new servers to use Redis]( https://github.com/pulibrary/princeton_ansible/issues/5343)

- [x] [Point our Rail application to the new Redis](https://github.com/pulibrary/princeton_ansible/issues/5344)

- [x] [Transition Web Servers to the new Redis Central Service after making sure the current jobs are completed](https://github.com/pulibrary/pdc_describe/issues/1928)

Clean up tickets

- [x] [Make Redis not critical on health.json](https://github.com/pulibrary/pdc_describe/issues/1929) 

- [x] [Monitor central Redis with check_mk](https://github.com/pulibrary/pdc_describe/issues/1930)

- [x] [Remove local redis from playbook and reprovision the machine](https://github.com/pulibrary/princeton_ansible/issues/5345)
