### ISSUE TITLE
Authentication / Authorization for MVP

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#304]
- [x] A user can log in using Princeton CAS
- [x] A user can have an ORCiD attached to their account
- [x] Only logged in users can see items in describe
- [x] A submitter can only edit objects they created
- [x] A superadmin can edit any object in any collection
- [x] A collection admin can edit any object in their collection
