### ISSUE TITLE
Describe Form: missing spaces in rendered migration data entries

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#617]
## Description

Tyler carefully recorded the spaces between separate "description" elements (in Dublin Core, the abstract and description) that were in Dublin Core, when translating these to Datacite "description:other" in the XML and PDC Describe form. We noticed that the spaces appeared in the form itself, but do not appear in the rendered record within PDC Describe. The legacy records are not yet available in PDC Discovery, so we don't know if there will be a similar issue when rendered there.

## To-Do
- [ ] @Twade968 Please add screenshots to this ticket that show 1) the space between descriptive sections in the form 2) the same space missing when the record is rendered in PDC Describe  

## Acceptance Criteria
- [ ] Investigate this issue to explore why the spaces are seen in the form but not in the rendering of the record
- [ ] The rendered record should have the same spaces that were entered to the form

**Comment by mccalluc** [comment]
During data entry it looks like:
<img width="522" alt="Screen Shot 2022-12-05 at 1 02 42 PM" src="https://user-images.githubusercontent.com/730388/205716786-5fadc93d-126c-4200-aa7e-875c7ce014c6.png">

When rendered it looks like:
<img width="863" alt="Screen Shot 2022-12-05 at 1 03 29 PM" src="https://user-images.githubusercontent.com/730388/205716906-89576c8a-b861-4c8f-bd69-92aaded8a782.png">

HTML's default is to collapse all spaces (space characters, tabs, and newlines), but this can be overridden with CSS.
