### ISSUE TITLE
Describe Form: Sign in for new users (ORCID landing page)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#648]
## Description

New users of the Describe Form are taken to a landing page where they may enter their ORCID ID. We would like to add text that explains why it would be preferable to enter your ORCID.

## Text
We notice you do not have an ORCID ID [this is why; hyperlink to the ORCID guide]

## To-do
- [ ] Neggin applies text to the ticket
- [ ] Neggin returns ticket assignment to Hannah
- [ ] Hannah refines ticket before handing to RDSS

**Comment by mccalluc** [comment]
Closing this issue: The text has been specified on  
- #750
